### ISSUE TITLE
.NETCore 2.0 Support?

### ISSUE THREAD

**Issue by xplatsolutions** [alastairtree/LazyCache#26] opened 2017-12-12 19:15 UTC
I saw the previous post but I couldn't find if eventually there is a code branch or -pre nuget regarding .NET Core 2.0 support, any update?

Thank you for the library, works amazingly nice!

**Comment by jpmckearin** [comment] 2018-01-19 07:31
https://github.com/alastairtree/LazyCache/issues/24

**Comment by RealDotNetDave** [comment] 2018-02-21 17:39
+1

**Comment by alastairtree** [comment] 2018-02-22 20:47
Duplicate of #24

**Closed by alastairtree** 2018-02-22 20:47 UTC

**Comment by alastairtree** [comment] 2018-03-04 10:11
There is now a pre release net standard version on Nugent.org. Let me know what you think.
