### ISSUE TITLE
how do I clean the cache items by  wildcard of a key

### ISSUE THREAD

**Issue by neozhu** [alastairtree/LazyCache#167] opened 2021-09-19 04:32 UTC
I save the query cache by the paging parameters and field conditions.
e.g. cache key :$"{entityName}-{pageIndex}-{pageSize}-{filters}" : "Customers-1-30-"
I need to clean these cache items when I update customers data. 
so, I want call cache.Remove("Customers-*")  or   any other solutions?

I saw that "Method 2 - Cancellation Tokens (could also be used to dispose a range of items)", but I use MediatR CQRS  pattern in my project, how to use CancellationTokenSource

**Comment by alastairtree** [comment] 2021-09-19 15:19
This is a duplicate of https://github.com/alastairtree/LazyCache/issues/74 so i will close it. Have a look at that as I have already proposed a way to achieve what you want.

**Closed by alastairtree** 2021-09-19 15:19 UTC
Labels: enhancement

**Comment by neozhu** [comment] 2021-09-20 12:14
thanks, I did it.
